#!/bin/bash

# Sane environment
unset DRI_PRIME VK_ICD_FILENAMES __NV_PRIME_RENDER_OFFLOAD \
	__GLX_VENDOR_LIBRARY_NAME __VK_LAYER_NV_optimus

# Check arguments
[ -z "$@" ] && notify-send -u critical "ERROR: At least 1 argument required!" \
&& exit 1

BAT_STATUS=$(cat /sys/class/power_supply/BAT*/status)

# make sure we have more than 1 active GPU
# Will the first card always be 0?
if [ -e /dev/dri/card1 ]; then
  # Check Xorg running
  # If not, assume using Wayland
  ! pidof {X,Xorg} > /dev/null && _not_xorg=1
  if [[ $BAT_STATUS =~ (Full|Charging|Unknown) ]]; then
    if [ ! $_not_xorg ] && [[ $(xrandr --listproviders) =~ "NVIDIA" ]]; then
      __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia  \
      __VK_LAYER_NV_optimus=NVIDIA_only "$@"
    elif [ $_not_xorg ] || [[ ! $(xrandr --listproviders) =~ "NVIDIA" ]]; then
      DRI_PRIME=1 "$@"
    fi
    exit
  fi

  # iGPU driver only loaded to pass fb to dGPU (NVIDIA)
  # so it's ICD will not load at all if we try to use it
  if [ ! $_not_xorg ] && [[ $(xrandr --listproviders) =~ "NVIDIA-0" ]]; then
    # Seems there's a performance issue with using
    # __NV_PRIME_RENDER_OFFLOAD=1 in NVIDIA mode
    __GLX_VENDOR_LIBRARY_NAME=nvidia  __VK_LAYER_NV_optimus=NVIDIA_only "$@"
    exit
  fi

  [ ! /sys/class/power_supply/BAT* ] && notify-send \
  "WARNING: Battery not detected, defaulting to iGPU" && _default=1

  # Use iGPU in Vulkan games (DXVK)
  if [[ ! $BAT_STATUS =~ (Full|Charging|Unknown) ]]; then
    for _f in /usr/share/vulkan/icd.d/*; do
      if [[ ! "$_f"  =~ "nvidia" ]]; then
        _VK_ICD+="$_f "
      fi
    done
    VK_ICD_FILENAMES="${_VK_ICD// /:}" "$@"
    exit
  fi
else
  notify-send "WARNING: Only 1 (active) GPU detected, continuing anyways." && \
  "$@"
fi
